# Generated by Django 2.1.7 on 2020-08-20 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lun06', models.BooleanField(default=False)),
                ('mar06', models.BooleanField(default=False)),
                ('mie06', models.BooleanField(default=False)),
                ('jue06', models.BooleanField(default=False)),
                ('vie06', models.BooleanField(default=False)),
                ('sab06', models.BooleanField(default=False)),
                ('lun07', models.BooleanField(default=False)),
                ('mar07', models.BooleanField(default=False)),
                ('mie07', models.BooleanField(default=False)),
                ('jue07', models.BooleanField(default=False)),
                ('vie07', models.BooleanField(default=False)),
                ('sab07', models.BooleanField(default=False)),
                ('lun08', models.BooleanField(default=False)),
                ('mar08', models.BooleanField(default=False)),
                ('mie08', models.BooleanField(default=False)),
                ('jue08', models.BooleanField(default=False)),
                ('vie08', models.BooleanField(default=False)),
                ('sab08', models.BooleanField(default=False)),
                ('lun09', models.BooleanField(default=False)),
                ('mar09', models.BooleanField(default=False)),
                ('mie09', models.BooleanField(default=False)),
                ('jue09', models.BooleanField(default=False)),
                ('vie09', models.BooleanField(default=False)),
                ('sab09', models.BooleanField(default=False)),
                ('lun10', models.BooleanField(default=False)),
                ('mar10', models.BooleanField(default=False)),
                ('mie10', models.BooleanField(default=False)),
                ('jue10', models.BooleanField(default=False)),
                ('vie10', models.BooleanField(default=False)),
                ('sab10', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=50)),
                ('edad', models.PositiveSmallIntegerField()),
                ('peso', models.PositiveSmallIntegerField()),
                ('estatura', models.PositiveSmallIntegerField()),
                ('perfil', models.CharField(max_length=3)),
                ('ritmo', models.PositiveSmallIntegerField()),
                ('tiros', models.PositiveSmallIntegerField()),
                ('pases', models.PositiveSmallIntegerField()),
                ('defensa', models.PositiveSmallIntegerField()),
                ('paradas', models.PositiveSmallIntegerField()),
                ('reflejos', models.PositiveSmallIntegerField()),
                ('posicionamiento', models.PositiveSmallIntegerField()),
                ('user', models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='jugador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jugador.Jugador'),
        ),
    ]
